spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed_api
    username: lanzoni
    password: MayaELilo150422
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9090
